Introduce /usr/local/bin and move some scripts

diff --git a/usr/local/bin/wrap-ntfy b/usr/local/bin/wrap-ntfy
--- a/usr/local/bin/wrap-ntfy
+++ b/usr/local/bin/wrap-ntfy
@@ -11,7 +11,7 @@
 #
 # Returns the exit code of the original command
 
-set -eu
+set -eu -o pipefail # use pipefail or the original exit code is discarded
 
 # https://stackoverflow.com/a/12451419
 exec 5>&1
@@ -25,9 +25,9 @@ curl_authz="Authorization: Bearer $NTFY_ACCESS_TOKEN"
 curl_endpoint=$NTFY_SERVER/$NTFY_TOPIC
 
 if [ $exit_code -eq 0 ]; then
-   curl -H "$curl_authz" -H prio:low -d "Script $NTFY_SCRIPT_NAME ran successfully" "$curl_endpoint"
+   curl --silent -H "$curl_authz" -H prio:min -H "Title: $NTFY_SCRIPT_NAME ran successfully" -d "$output" "$curl_endpoint"
 else
-   curl -H "$curl_authz" -H tags:warning -d "$output" "$curl_endpoint"
+   curl --silent -H "$curl_authz" -H tags:warning -H "Title: $NTFY_SCRIPT_NAME failed" -d "$output" "$curl_endpoint"
 fi
 
 exit $exit_code
