Update byzanz scripts

diff --git a/home/.local/bin/byzanz-record-window b/home/.local/bin/byzanz-record-window
--- a/home/.local/bin/byzanz-record-window
+++ b/home/.local/bin/byzanz-record-window
@@ -1,53 +1,51 @@
 #!/bin/bash
 
-# AUTHOR:   (c) Rob W 2012, modified by MHC (http://askubuntu.com/users/81372/mhc)
+# AUTHOR:   (c) Rob W 2012, modified by MHC (http://askubuntu.com/users/81372/mhc), modified by Kap
 # NAME:     GIFRecord 0.1
 # DESCRIPTION:  A script to record GIF screencasts.
 # LICENSE:  GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
-# DEPENDENCIES:   byzanz,gdialog,notify-send (install via sudo add-apt-repository ppa:fossfreedom/byzanz; sudo apt-get update && sudo apt-get install byzanz gdialog notify-osd)
+# DEPENDENCIES:   byzanz,zenity,notify-send
+
+set -euo pipefail
 
 # Time and date
-TIME=$(date +"%Y-%m-%d_%H%M%S")
+time=$(date +"%Y-%m-%d_%H%M%S")
 
 # Delay before starting
-DELAY=5
+delay=5
 
 # Standard screencast folder
-FOLDER="$HOME/tmp"
-
-# Default recording duration
-DEFDUR=10
+folder="$HOME/tmp"
 
 # Sound notification to let one know when recording is about to start (and ends)
 beep() {
     paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
 }
 
-# Custom recording duration as set by user
-USERDUR=$(gdialog --title "Duration?" --inputbox "Please enter the screencast duration in seconds" 200 100 2>&1)
-
-# Duration and output file
-if [ $USERDUR -gt 0 ]; then
-    D=$USERDUR
+duration=
+userdur=$(zenity --entry --title "Duration?" --text "Please enter the screencast duration in seconds.")
+if [ $? -eq 0 ]; then
+    duration=$userdur
 else
-    D=$DEFDUR
+    echo "Aborting.."
+    exit 1
 fi
 
 # Window geometry
-XWININFO=$(xwininfo)
-read X < <(awk -F: '/Absolute upper-left X/{print $2}' <<< "$XWININFO")
-read Y < <(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$XWININFO")
-read W < <(awk -F: '/Width/{print $2}' <<< "$XWININFO")
-read H < <(awk -F: '/Height/{print $2}' <<< "$XWININFO")
+xwininfo=$(xwininfo)
+read x < <(awk -F: '/Absolute upper-left X/{print $2}' <<< "$xwininfo")
+read y < <(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$xwininfo")
+read w < <(awk -F: '/Width/{print $2}' <<< "$xwininfo")
+read h < <(awk -F: '/Height/{print $2}' <<< "$xwininfo")
 
-# Notify the user of recording time and delay
-notify-send "GIFRecorder" "Recording duration set to $D seconds. Recording will start in $DELAY seconds."
+# notify the user of recording time and delay
+notify-send "Byzanz" "Recording duration set to $duration seconds.\nRecording will start in $delay seconds."
 
-#Actual recording
-sleep $DELAY
+file_path="$folder/recording_$time.gif"
+
+sleep $delay
 beep
-byzanz-record -c --verbose --delay=0 --duration=$D --x=$X --y=$Y --width=$W --height=$H "$FOLDER/GIFrecord_$TIME.gif"
+byzanz-record --cursor --delay=0 --duration=$duration --x=$x --y=$y --width=$w --height=$h "$file_path"
 beep
 
-# Notify the user of end of recording.
-notify-send "GIFRecorder" "Screencast saved to $FOLDER/GIFrecord_$TIME.gif"
+notify-send "Byzanz" "Recording saved to $file_path."
