Greatly simplify vault-mount - thanks cryptsetup team!

diff --git a/home/.local/bin/vault-mount b/home/.local/bin/vault-mount
--- a/home/.local/bin/vault-mount
+++ b/home/.local/bin/vault-mount
@@ -2,9 +2,9 @@
 
 set -uo pipefail
 
-loop_file=${1:-}
+vault_file=${1:-}
 
-if [ -z "$loop_file" ]; then
+if [ -z "$vault_file" ]; then
     error_code=64
     echo "Please pass the vault file path as first parameter (error: $error_code)"
     exit $error_code
@@ -18,66 +18,31 @@ if [ -z "$mount_point" ]; then
     exit $error_code
 fi
 
-dev_loop=""
-existing_loop=$(losetup -j "$loop_file")
+luks_status=$(sudo cryptsetup status vault)
 
+if [ "$?" -eq 0 -o "$?" -eq 4 ]; then
+    matches_count=$(echo "$luks_status" | grep -c 'read/write')
 
-if [ -z "$existing_loop" ] ; then
-    tmp_loop_dev=$(sudo losetup -f)
-    if [ "$?" = 0 ]; then
-        echo "Mounting vault on $dev_loop..."
-        sudo losetup $tmp_loop_dev $loop_file
-        if [ "$?" = 0 ]; then
-            dev_loop=$tmp_loop_dev
-        fi
-    else
-        echo "Error: cannot retrieve temporary loop device"
-    fi
-else
-    dev_loop=$(echo $existing_loop | awk -F":" '{ print($1) }')
-    echo "The file $loop_file is already mounted on $dev_loop";
-fi
+    if [ "$matches_count" -lt 1 ]; then
+        sudo cryptsetup open --type luks1 $vault_file vault
 
+        if [ "$?" -eq 0 ]; then
+            mkdir -p $mount_point
+            sudo mount /dev/mapper/vault $mount_point
 
-is_opened=false
-if $(sudo cryptsetup isLuks $dev_loop); then
-    luks_uuid=$(sudo cryptsetup luksUUID $dev_loop | tr -d -)
-    if test -b /dev/disk/by-id/dm-uuid-*$luks_uuid*; then
-        is_opened=true
-    fi
-fi
-
-if [ "$is_opened" = "false" ]; then
-    if [ -n "$dev_loop" ]; then
-        luks_status=$(sudo cryptsetup status vault)
-        if [ "$?" -eq 0 -o "$?" -eq 4 ]; then
-            matches_count=$(echo "$luks_status" | grep -c 'read/write')
-            if [ "$matches_count" -lt 1 ]; then
-
-                sudo cryptsetup luksOpen $dev_loop vault
-
-                if [ "$?" -eq 0 ]; then
-                    mkdir -p $mount_point
-                    sudo mount /dev/mapper/vault $mount_point
-
-                    if [ "$?" -eq 0 ]; then
-                        echo "Vault mounted on $mount_point"
-                    else
-                        echo "Error: mount exited with $?"
-                    fi
-
-                else
-                    echo "Error: cryptsetup exited with $?"
-                fi
+            if [ "$?" -eq 0 ]; then
+                echo "Vault mounted on $mount_point"
             else
-                echo "$luks_status"
+                echo "Error: mount exited with $?"
             fi
         else
-            echo "Error: cannot retrieve vault status"
+            echo "Error: cryptsetup exited with $?"
         fi
     else
-        echo "Error: cannot detect the mounted loop device"
+        echo "$luks_status"
     fi
+else
+    echo "Error: cannot retrieve vault status"
 fi
 
 exit $?
